;; Generated by Bangla Compiler
;; Target: WebAssembly Text Format (.wat)

(module
   (import "env" "print_i32" (func $print_i32 (param i32)))
   (import "env" "print_str" (func $print_str (param i32 i32)))

   (memory (export "memory") 1)

   (func $main (export "main")
      ;; Local variables
      (local $var_বয়স i32)
      (local $var_নাম i32)
      (local $var_পতাকা i32)

      ;; Statements
      i32.const 22
      local.set $var_বয়স
      i32.const 0 ;; string ptr
      local.set $var_নাম
      i32.const 0
      local.set $var_পতাকা
      local.get $var_বয়স
      i32.const 18
      i32.ge_s
      if
         i32.const 1
         local.set $var_পতাকা
         i32.const 0 ;; string ptr
         call $print_i32
      else
         i32.const 0
         local.set $var_পতাকা
         i32.const 0 ;; string ptr
         call $print_i32
      end
      local.get $var_নাম
      call $print_i32
      local.get $var_পতাকা
      call $print_i32
   )
)
