package codegen;

import ast.ASTNode;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class WasmCodeGenerator {

    public String generateWasmCode(ASTNode.ProgramNode program, String outputPath) {
        StringBuilder sb = new StringBuilder();

        sb.append(";; Generated by Bangla Compiler\n");
        sb.append(";; Target: WebAssembly Text Format (.wat)\n\n");
        sb.append("(module\n");

        sb.append("   (import \"env\" \"print_i32\" (func $print_i32 (param i32)))\n");
        sb.append("   (import \"env\" \"print_str\" (func $print_str (param i32 i32)))\n\n");
        sb.append("   (memory (export \"memory\") 1)\n\n");

        sb.append("   (func $main (export \"main\")\n");

        if (program != null) {
            sb.append("      ;; Local variables\n");
            for (ASTNode stmt : program.statements) {
                if (stmt instanceof ASTNode.DeclNode) {
                    ASTNode.DeclNode decl = (ASTNode.DeclNode) stmt;
                    sb.append("      (local $var_").append(decl.name).append(" i32)\n");
                }
            }

            sb.append("\n      ;; Statements\n");
            for (ASTNode stmt : program.statements) {
                sb.append(genStmt(stmt, 6));
            }
        }

        sb.append("   )\n");
        sb.append(")\n");

        String wasmCode = sb.toString();
        try {
            File file = new File(outputPath);
            if (file.getParentFile() != null) {
                file.getParentFile().mkdirs();
            }
            Files.write(Paths.get(outputPath), wasmCode.getBytes(StandardCharsets.UTF_8));
        } catch (Exception e) {
            System.err.println("Failed to write WebAssembly target code file: " + e.getMessage());
        }
        return wasmCode;
    }

    private String genStmt(ASTNode node, int indentLevel) {
        String indent = " ".repeat(indentLevel);
        StringBuilder sb = new StringBuilder();

        if (node instanceof ASTNode.DeclNode) {
            ASTNode.DeclNode decl = (ASTNode.DeclNode) node;
            sb.append(genExpr(decl.expr, indentLevel));
            sb.append(indent).append("local.set $var_").append(decl.name).append("\n");
        }
        else if (node instanceof ASTNode.AssignNode) {
            ASTNode.AssignNode assign = (ASTNode.AssignNode) node;
            sb.append(genExpr(assign.expr, indentLevel));
            sb.append(indent).append("local.set $var_").append(assign.name).append("\n");
        }
        else if (node instanceof ASTNode.PrintNode) {
            ASTNode.PrintNode printNode = (ASTNode.PrintNode) node;
            sb.append(genExpr(printNode.expr, indentLevel));
            sb.append(indent).append("call $print_i32\n");
        }
        else if (node instanceof ASTNode.IfNode) {
            ASTNode.IfNode ifNode = (ASTNode.IfNode) node;
            sb.append(genExpr(ifNode.condition, indentLevel));
            sb.append(indent).append("if\n");
            for (ASTNode s : ifNode.thenBranch) {
                sb.append(genStmt(s, indentLevel + 3));
            }
            if (!ifNode.elseBranch.isEmpty()) {
                sb.append(indent).append("else\n");
                for (ASTNode s : ifNode.elseBranch) {
                    sb.append(genStmt(s, indentLevel + 3));
                }
            }
            sb.append(indent).append("end\n");
        }
        else if (node instanceof ASTNode.WhileNode) {
            ASTNode.WhileNode whileNode = (ASTNode.WhileNode) node;
            sb.append(indent).append("block\n");
            sb.append(indent).append("  loop\n");
            sb.append(genExpr(whileNode.condition, indentLevel + 4));
            sb.append(indent).append("    i32.eqz\n");
            sb.append(indent).append("    br_if 1\n");
            for (ASTNode s : whileNode.body) {
                sb.append(genStmt(s, indentLevel + 4));
            }
            sb.append(indent).append("    br 0\n");
            sb.append(indent).append("  end\n");
            sb.append(indent).append("end\n");
        }
        return sb.toString();
    }

    private String genExpr(ASTNode node, int indentLevel) {
        String indent = " ".repeat(indentLevel);
        StringBuilder sb = new StringBuilder();

        if (node instanceof ASTNode.NumberNode) {
            sb.append(indent).append("i32.const ").append(((ASTNode.NumberNode) node).value).append("\n");
        }
        else if (node instanceof ASTNode.StringNode) {
            sb.append(indent).append("i32.const 0 ;; string ptr\n");
        }
        else if (node instanceof ASTNode.VarNode) {
            sb.append(indent).append("local.get $var_").append(((ASTNode.VarNode) node).name).append("\n");
        }
        else if (node instanceof ASTNode.BinOpNode) {
            ASTNode.BinOpNode bin = (ASTNode.BinOpNode) node;
            sb.append(genExpr(bin.left, indentLevel));
            sb.append(genExpr(bin.right, indentLevel));
            switch (bin.op) {
                case "+": sb.append(indent).append("i32.add\n"); break;
                case "-": sb.append(indent).append("i32.sub\n"); break;
                case "*": sb.append(indent).append("i32.mul\n"); break;
                case "/": sb.append(indent).append("i32.div_s\n"); break;
                case "==": sb.append(indent).append("i32.eq\n"); break;
                case "!=": sb.append(indent).append("i32.ne\n"); break;
                case "<": sb.append(indent).append("i32.lt_s\n"); break;
                case ">": sb.append(indent).append("i32.gt_s\n"); break;
                case "<=": sb.append(indent).append("i32.le_s\n"); break;
                case ">=": sb.append(indent).append("i32.ge_s\n"); break;
            }
        }
        return sb.toString();
    }
}